apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: devops-portfolio
  namespace: flux-system
spec:
   image: fayemameibra/devops-portfolio
   interval: 5m
   secretRef:
     name: registry-credentials