apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: portfolio
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: faye.mame-ibra@ugb.edu.sn
        name: fluxcdbot
        messageTemplate: |
          Update images
          {{ range .Changed.Changes }}
          - {{ . }}
          {{ end }}
    push:
      branch: main
  update:
    path: ./applications/portfolio/base
    strategy: Setters