apiVersion: v1
kind: Secret
metadata:
 name: registry-credentials
 namespace: flux-system
type: Opaque
data:
 docker-server: aHR0cHM6Ly9odWIuZG9ja2VyLmNvbS8K
 docker-username: ZmF5ZW1hbWVpYnJhCg==
 docker-password: MTgyNjE4NTkyMDAxRkB5ZQo=