apiVersion: v1
kind: Secret
metadata:
    name: nextjs-secret
    namespace: nextjs-app
data:
    DB_PASSWORD: ENC[AES256_GCM,data:mqRd+l/K9opcWXWnQDOwYA==,iv:NGcnyqrJ1z5KS8JFcniWxxgAQOf0xtIuCqBPOUY4J9A=,tag:M05giSM/A/hpjAWnGCBb8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV3hVMlF4S1IveEZyU0cr
            V3NReTNOSC9IR29BWWY4OHJNYmxIanlLbUJRCmV6WThJcklRRVFOMXNZYmppNFlr
            UDR1cVNEYkd2L3FCZlBSbGNzdVpjd0EKLS0tIFR1WWQzOWw2ck45OWNZakNLd1g5
            ZEt4cnMxTkdob1BISUJJaVkyeGVKd0UKckHBiHMb4/APMeScsGnKlNgpIb0bBAB4
            BCoZlMcN532i03EKknHW6JI01y47I5wjCwyY7+pdfl7xI4wIN5ZtQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0dcjgcsthdc5lragu7qfct8whlp7mnsj6ggsy3pj65qzfglwuesvc37r4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T22:25:00Z"
    mac: ENC[AES256_GCM,data:huvuvH33jOSwtnTWlf4wyweDL1F6XRUwgb1eEiGDFHUU9/urExJRujMTGP3W3DexxYyiv5NgbNvUDejCGYb0cJhkwS+4T2HzwltHd+JDG0wWB9GdKuDvgqpFsIZaC5mCba8eN0QpKTfW+kNZCQ4YRwbKk0Riw1jy6qIw+bKSSdo=,iv:4rNe/Juei4o9Tr0q9YlHFKq64uy11N+jzZZAJbYbWz0=,tag:vV1OgiNsKlZMBealxj8meA==,type:str]
    version: 3.13.3
