# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: porto-folio

# spec:
#   template:
#     spec:
#       containers:
#         - name: porto-folio
#           image: mif/porto-folio:1.1.0


apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nextjs-app
  namespace: nextjs-app
spec:
  template:
    spec:
      containers:
        - name: my-nextjs-app
          image: fayemameibra/devops-portfolio:v0.0.2