apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: postgres
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9L4g07mSKdX56gZzFAWBXw==,iv:GGpM77pBWP/NGdUXgSrAf0nCIu1c7sw3dsqn8CM1fnM=,tag:c8mCubwalqRrRW8YKfHKog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZnJkNjRyeVpFaDhCcW13
            aGJKS2ZTUll2d0h1ajgyYkpkcXNsd2FJOWdjCnI3MDNxdUQzMEVHcXNyaVJxcFFL
            WWduL3NMOFVMTmpDWllxb2JXTHRtT3MKLS0tIFVTNW9pQWxVRmx4MlQ0c2RzTVRX
            QyttamQxa1dMR0V6SE8wck1JTVoxckkKplZYwuUyaN2m3pWR6Q8bKceQkpevDAsK
            K8OTjCxXjlE51Fq27GfSUF5moB7lp4m/CguFq1HDgFh/HD2/GTeKXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0dcjgcsthdc5lragu7qfct8whlp7mnsj6ggsy3pj65qzfglwuesvc37r4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T22:27:04Z"
    mac: ENC[AES256_GCM,data:lL41CNF5EiKjZK+XOk1Rciu0STb7ESuaIvMMs5KAYmsqkzcOvxS1KKztKbCJ0odDQaK5xpVB86dDk0Rp34YYGcafNFOUvAiO29YcwRuK0N+hhy3JBCU9piARBGEYcoI0u8umwlbiU2BSvK2VnVJpjhpJE1JsObnduC71ic+C68k=,iv:ihqEAk3NHWeuqIWxElTPlZRiV5Zl3ly7eQ28ePqea5U=,tag:xIpJws5wZDNYhnSjvr5xXA==,type:str]
    version: 3.13.3
